### ISSUE TITLE
Notice banner and navigation bar not resizing on narrower screens

### ISSUE THREAD

**Issue by bill-95** [Basis-Cash/basiscash-frontend#7]
On mobile screens, the notice on the home page does not fit the width of the screen. 
![example](https://user-images.githubusercontent.com/13008126/101939386-c10fb800-3b99-11eb-95c6-c6615bf8e966.PNG)

Also the navigation bar cuts off on the right side of a narrower screen.
![example 2](https://user-images.githubusercontent.com/13008126/101946440-d2f65880-3ba3-11eb-91a4-d638da09ce73.PNG)

**Comment by bill-95** [comment]
#8 pull request

**Comment by summersmooth** [comment]
✅ Merged. Thanks for the contribution!
